name: Deploy AdmireSoftech Frontend

on:
    push:
        branches:
            - main

permissions:
    id-token: write
    contents: read


jobs:
    deploy:
        name: Build and Deploy to AWS
        runs-on: ubuntu-latest

        steps:
            # Checkout the repository
            - name: Checkout code
              uses: actions/checkout@v4
            

            # Set up Node.js
            - name: setup Node.js
              uses: actions/setup-node@v4
              with:
                 node-version: '22'
                 cache: 'npm'

            
            # Install dependencies
            - name: Install dependencies
              run: npm ci

            # create  dotenv file using secrets for production
            - name: Create .env file
              run: |
                echo "VITE_API_URL=${{ secrets.VITE_API_URL }}" > .env

            # make build for production    
            - name : build the project
              run: npm run build

            # assume github actions IAM role to get temporary AWS credentials
            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
                aws-region: ${{ secrets.AWS_REGION }}

            # deploy to S3 bucket
            - name: Deploy to S3 bucket
              run: |
                aws s3 sync ./dist s3://${{ secrets.S3_BUCKET_NAME }} --delete

            # invalidate CloudFront cache
            - name: Invalidate CloudFront cache
              run: |
                aws cloudfront create-invalidation \
                    --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} \
                    --paths "/*"